### ISSUE TITLE
Help icon isn't styled properly

### ISSUE THREAD

**Issue by aadishsamir123** [RyanLua/ClassroomDarkMode#96]
### Description

Help icon in bottom-right corner is not styled properly

### Expected behavior

The help button should be dark like the rest of the website

### Actual behavior

It looks white and weird

<img width="64" alt="SCR-20240915-octa" src="https://github.com/user-attachments/assets/6aa31d44-c7fe-4fea-8608-10dbd3920bb6">

### Steps to reproduce

1. Go to Google Classroom
2. Look in bottom-right corner

### Other details

Using Vivaldi browser

### Extension Version

0.1.2

### Platform

Other

### Browser Version

6.9.3447.44 (Stable channel) (arm64) 

### Severity

Moderate

### Code of Conduct

- [X] I have read and agree to the project's [Code of Conduct](https://github.com/RyanLua/ClassroomDarkMode?tab=coc-ov-file)

**Comment by RyanLua** [comment]
Thanks for reporting again. This fix will be included in the next version, 0.1.4. I can't quite push it yet since 0.1.3 needs approval still.
